# Generated by Django 5.1.3 on 2024-11-17 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('espacio', models.CharField(choices=[('Baloncesto', 'Baloncesto'), ('Fútbol', 'Fútbol'), ('Padel', 'Padel'), ('Piscina1', 'Piscina1'), ('Piscina2', 'Piscina2')], default='Padel', max_length=20)),
                ('momento_inicio', models.DateTimeField()),
                ('momento_fin', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'reserva',
                'verbose_name_plural': 'reservas',
                'db_table': 'reservas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='LineaReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_reservas.reserva')),
            ],
        ),
    ]
