# Generated by Django 5.1.1 on 2024-11-11 22:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_reservas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='date',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='pista',
        ),
        migrations.AddField(
            model_name='reserva',
            name='espacio',
            field=models.CharField(choices=[('Baloncesto', 'Baloncesto'), ('Fútbol', 'Fútbol'), ('Padel', 'Padel'), ('Piscina1', 'Piscina1'), ('Piscina2', 'Piscina2')], default='Padel', max_length=20),
        ),
        migrations.AddField(
            model_name='reserva',
            name='momento_fin',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='momento_inicio',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
