# Generated by Django 5.1.1 on 2024-11-10 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_reservas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=50)),
                ('metodo_pago', models.CharField(max_length=50)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_reservas.reserva')),
            ],
            options={
                'verbose_name': 'pago',
                'verbose_name_plural': 'pagos',
                'db_table': 'pagos',
                'ordering': ['id'],
            },
        ),
    ]
